#!/bin/sh

TMUX_UP=tmux-up
VERSION=0.6.0-pre

if [ $# -ne 1 ] && [ ! -f '.tmux.conf' ]
then
  echo "$0: missing file operand"
  echo "Try '$0 --help' for more information."
  exit 1
fi

if [ "$1" = '-h' ] || [ "$1" = '--help' ]
then
  cat <<-USAGE
		Usage: $0 [FILE]
		Attach to a newly bootstrapped or existing tmux session.

		The FILE argument is used to bootstrap the new tmux session if it doesn't
		already exist. It must contain tmux-compatible commands, which will be
		passed to tmux. Defaults to: tmux.conf OR .tmux.conf

		  --help     display this help and exit
		  --version  output version information and exit
	USAGE
  exit 0
fi

if [ "$1" = '-v' ] || [ "$1" = '--version' ]
then
  cat <<-EOF
		$TMUX_UP $VERSION
		Copyright (C) 2015 James Ottaway
		License MIT: <http://opensource.org/licenses/MIT>.
		This is free software: you are free to change and redistribute it.
		There is NO WARRANTY, to the extent permitted by law.
	EOF
  exit 0
fi

if [ -f "$1" ]
then
  FILE=$1
elif [ -f 'tmux.conf' ]
then
  FILE='tmux.conf'
elif [ -f '.tmux.conf' ]
then
  FILE='.tmux.conf'
else
  echo "$0: cannot stat ‘${1:-tmux.conf}’: No such file"
  exit 1
fi

BASE=$(basename "$PWD" | sed 's/[^a-zA-Z0-9\-]//g')
NAME=$(basename "$FILE" .conf)

if [ "$NAME" = 'tmux' ] || [ "$NAME" = '.tmux' ]
then
  SESSION=$BASE
else
  SESSION=$BASE/$NAME
fi

if ! tmux has-session -t "$SESSION" > /dev/null 2>&1
then
  TMUX='' tmux new-session -d -s "$SESSION"
  xargs -L1 tmux < "$FILE"
  tmux select-window -t 2 > /dev/null 2>&1
  tmux select-window -t 1
fi

if [ -z "$TMUX" ]
then
  tmux attach -t "$SESSION"
else
  tmux switch-client -t "$SESSION"
fi
