#!/bin/sh

TMUX_UP=tmux-up
VERSION=0.7.0-pre

if [ $# -ne 1 ] && [ ! -f '.tmux.conf' ]
then
  echo "$0: missing file operand"
  echo "Try '$0 --help' for more information."
  exit 1
fi

if [ -n "$TMUX" ]
then
  echo "$0: cannot run within an existing tmux session"
  exit 1
fi

if [ "$1" = '-h' ] || [ "$1" = '--help' ]
then
  cat <<-USAGE
		Usage: $0 [FILE]
		Attach to a newly bootstrapped or existing tmux session.

		The FILE argument is used to bootstrap the new tmux session if it doesn't
		already exist. It must contain tmux-compatible commands, which will be
		passed to tmux. Defaults to: tmux.conf OR .tmux.conf

		  --help     display this help and exit
		  --version  output version information and exit
	USAGE
  exit 0
fi

if [ "$1" = '-v' ] || [ "$1" = '--version' ]
then
  cat <<-EOF
		$TMUX_UP $VERSION
		Copyright (C) 2015 James Ottaway
		License MIT: <http://opensource.org/licenses/MIT>.
		This is free software: you are free to change and redistribute it.
		There is NO WARRANTY, to the extent permitted by law.
	EOF
  exit 0
fi

TMUX_DIR='.tmux'
GLOBAL_DIR="$HOME/$TMUX_DIR"
BASE=$(basename "$PWD" | sed 's/[^a-zA-Z0-9\-]//g')

if [ -z "$1" ]
then
  FILES="$PWD/tmux.conf $PWD/.tmux.conf $HOME/.tmux-up/$BASE.conf $HOME/.tmux-up.conf"
else
  FILES="$1 $PWD/$1 $PWD/.tmux/$1 $HOME/.tmux-up/$BASE/$1 $HOME/.tmux-up/$1"
fi

for file in $FILES
do
  if [ -f $file ]
  then
    FILE=$file
    break
  fi
done

if [ -z $FILE ]
then
  echo "$0: cannot stat ‘${1:-tmux.conf}’: No such file"
  exit 1
fi

NAME=$(basename "$FILE" .conf)

if [ -z "$BASE" ]
then
  SESSION=$NAME
elif [ "$NAME" = 'tmux' ] || [ "$NAME" = '.tmux' ]
then
  SESSION=$BASE
else
  SESSION=$BASE/$NAME
fi

if tmux has-session -t "$SESSION" > /dev/null 2>&1
then
  tmux attach -t "$SESSION"
else
  tmux new-session -d -s "$SESSION"
  tmux source-file "$FILE"
  for i in 2 1 0; do
    tmux select-window -t $i > /dev/null 2>&1
  done
  tmux attach-session -t "$SESSION"
fi
